### ISSUE TITLE
Not enough allowance

### ISSUE THREAD

**Issue by testingmediation** [RichardAtCT/1inch_wrapper#15]
Hello,

I am having difficulty doing a basic swap and I'm not sure I understand why

Here's the error message I'm getting:

`{"statusCode":400,"error":"Bad Request","description":"Not enough allowance. Amount: 1000000. Allowance: 0. Spender: 0x1111111254eeb25477b68fb85ed929f73a960582","meta":[{"type":"amount","value":"1000000"},{"type":"allowance","value":"0"}],"requestId":"2ba5f7dd-9064-4824-abda-cbece14595ae"}`

Thing is I am running the get_approve & get_allowance before the get_swap function, but the allowance amount stays at 0 for some reason. According to the 1inch docs, if no amount is supplied in approve, infinite allowance is assumed. I am using a metamask waller with infura node.

```
exchange = OneInchSwap(public_key)
helper = TransactionHelper(rpc_url, public_key, private_key)
oracle = OneInchOracle(rpc_url, chain='ethereum')

exchange.get_approve("USDT")
exchange.get_allowance("USDT")

exchange.get_swap(from_token_symbol='USDT', to_token_symbol='ETH', amount=1, slippage=0.5)
```

**Comment by RichardAtCT** [comment]
You need to submit the get_approve tx. e.g. here: https://gist.github.com/RichardAtCT/434a1bc3bd493be8f6305048c455bc07
