### ISSUE TITLE
GAS

### ISSUE THREAD

**Issue by rob000000** [RichardAtCT/1inch_wrapper#16]
Is it possible to introduce the gas limit and price of gwei you wanna pay fot the tx?

**Comment by RichardAtCT** [comment]
You can set your own gas parameters by editing the built_tx.

**Comment by rob000000** [comment]
And how can I do It?



Roberto Ortas

**Comment by RichardAtCT** [comment]
Just edit the dictionary produced by build_tx and change the gas parameters
that you want to change.
