### ISSUE TITLE
Authentification needed

### ISSUE THREAD

**Issue by Nick2Nik** [RichardAtCT/1inch_wrapper#19]
The public Swap API api.1inch.io is deprecated. To continue using the Swap API please migrate to the [1inch Developer Portal](https://portal.1inch.dev/)

**Comment by RichardAtCT** [comment]
Open to pull requests if anyone wants to do the migration!

**Comment by kaeptnb** [comment]
1inch_wrapper needs to be adapted for the 1inch api change :( who do i need to pay? ;)

**Comment by RichardAtCT** [comment]
Only thing pending is handling the gas cost calculations. If you have any
ideas (ideally an API) let me know!
