### ISSUE TITLE
Dependency - requests

### ISSUE THREAD

**Issue by snub-fighter** [RichardAtCT/1inch_wrapper#4]
1inch.py is looking for the METADATA file in requests  `Lib\site-packages\requests-2.28.1.dist-info`

requests-2.25.1.dist-info has the METADATA file but 2.28 does not.   

**Workaround**
`pip install 1inch.py --ignore-installed requests`

**Comment by RichardAtCT** [comment]
Would you mind submitting a PR to fix it? Don't think the build needs 2.28 particularly :) @snub-fighter
