### ISSUE TITLE
1inch Fusion version

### ISSUE THREAD

**Issue by tnd3** [RichardAtCT/1inch_wrapper#8]
Richard,

Nice 1inch wrapper for Python! 

Noticed you updated it yesterday.
Please could you make a short version for the new @1inch Fusion mode = **zero gas fees** etc..
https://1inch.io/fusion

https://github.com/1inch/fusion-sdk
**how-to-swap-with-fusion-mode**
```
const makerPrivateKey = '0x123....'
const makerAddress = '0x123....'

const nodeUrl = '....'

const blockchainProvider = new PrivateKeyProviderConnector(
    makerPrivateKey,
    new Web3(nodeUrl)
)

const sdk = new FusionSDK({
    url: 'https://fusion.1inch.io',
    network: 1,
    blockchainProvider
})

sdk.placeOrder({
    fromTokenAddress: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', // WETH
    toTokenAddress: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48', // USDC
    amount: '50000000000000000', // 0.05 ETH
    walletAddress: makerAddress
}).then(console.log)
```

Thanks

**Comment by amitkarpe** [comment]
"Fusion version" will be great addition.

**Comment by RichardAtCT** [comment]
I've had a look and it is a bigger project than I have time for at the moment. If anyone finds a python implementation I am happy to adapt it for the wrapper...

**Comment by tnd3** [comment]
These Python libraries may help (active project):

:iphone: :phone:
See the [TalkyTrader ](https://talky.readthedocs.io/en/latest/)project by [@mraniki](https://github.com/mraniki) here:
https://github.com/mraniki/tt

Python DEX Token Swap Library:
https://github.com/mraniki/dxsp
